name: Unity Activation (Generate ALF)

on:
  workflow_dispatch:

jobs:
  activation:
    name: Generate .alf file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate license request
        uses: game-ci/unity-request-activation@v2
        with:
          unityVersion: 2022.3.15f1

      - name: Upload .alf file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity_v2022.3.15f1.alf
          path: ./*.alf
